### PR TITLE
Multiple segments in page slug.

### PR DESCRIPTION
**Pull request by joachimVT**
Edit front end routes. This Makes it possible to assign page slugs with multiple segments. 
example.com/segment1/segment2/

### CODE REVIEW

**Comment by nWidart** [comment]
Doesn't the `?` in the route parameter just means the parameter is optional ? 

Ie: http://laravel.com/docs/5.1/routing#parameters-optional-parameters

The way laravel route::resource works is something like `{uri}/{one?}/{two?}/{three?}` etc.

**Comment by joshbrw** [comment]
Isn't it the `.*` the different bit?

**Comment by nWidart** [comment]
Oh I didn't see that. Correct that's new too, but I still don't see the point.

Why not do it as laravel does it ?

**Comment by joachimVT** [comment]
How does laravel make the slug dynamic? It would be nice to have no limitations in the segments you use. In the example above that's not possible ?

**Comment by nWidart** [comment]
Thanks, I introduced this in 25ec5f9e141aba19c1174ad6fdf9d0dfcbc89b58 without the `?` in the uri.

**Comment by simonfunk** [comment]
why do you need have several segments? to build a specific structure
or just because it wasn't possible with menu hierarchy?

**Pull request closed without merging**
